# Generated by Django 4.1.7 on 2023-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home/Slider_banner')),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
