# Generated by Django 4.1.7 on 2023-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_slider_banner_button_name_slider_banner_button_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='home/service')),
                ('heading', models.CharField(blank=True, max_length=40, null=True)),
                ('subcontent', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
