# Generated by Django 4.1.7 on 2023-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mission', models.CharField(max_length=300)),
                ('vision', models.CharField(max_length=300)),
            ],
        ),
    ]
