# Generated by Django 4.1.7 on 2023-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_mission_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission_vision',
            name='why_choose_us',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mission_vision',
            name='mission',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mission_vision',
            name='vision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
