# Generated by Django 4.1.7 on 2023-05-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mission_vision_why_choose_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home/Session_types')),
            ],
        ),
    ]
