# Generated by Django 4.1.7 on 2023-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_session_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_types',
            name='url',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
