# Generated by Django 4.1.7 on 2023-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_session_types_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='about_us')),
            ],
        ),
    ]
