# Generated by Django 4.1.7 on 2023-05-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
