# Generated by Django 4.1.7 on 2023-05-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_about_us_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContantForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
