# Generated by Django 4.1.7 on 2023-05-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_contantform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContantForm',
            new_name='ContactForm',
        ),
    ]
